config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root to: "meal_plans#index"

  resources :meal_plans, path: "/meal-plans" do
    collection do
      get "past", to: "meal_plans#past_meal_plans"
    end
    member do
      get "shopping-list", to: "meal_plans#generate_shopping_list"
    end
  end

  resources :recipe_books, path: "/recipe-books" do
    collection do
      get "search", to: "recipe_books#search"
    end
  end
  resources :recipes

  resources :meals do
    member do
      put "update_eaten_status"
    end
  end

  resources :labels
end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
  has_many :meals, dependent: :delete_all
  has_many :recipes, through: :meals

  validates :start_date, :end_date, presence: true
  validate :end_after_start?

  scope :past, -> { where("end_date < ?", Time.zone.today) }
  scope :future, -> { where("start_date > ?", Time.zone.today) }
  scope :current, -> { where("start_date <= ? and end_date >= ?", Time.zone.today, Time.zone.today) }

  def complete?
    meals.map(&:eaten?).all?
  end

  private

  def end_after_start?
    errors.add(:end_date, "must be after start date") if end_date < start_date
  end
end

app/controllers/meal_plans_controller.rb
class MealPlansController < ApplicationController
  before_action :set_meal_plan, only: %i[edit update destroy generate_shopping_list]
  before_action :available_recipes, only: %i[create edit]

  def index
    @meal_plans = MealPlan.all
    @current_meal_plan = MealPlan.current.first || MealPlan.last
  end

  def new
    @meal_plan = MealPlan.new
  end

  def edit; end

  def create
    @meal_plan = MealPlan.new(
      start_date: meal_plan_params[:start_date],
      end_date: meal_plan_params[:end_date],
      recipe_ids: meal_plan_params.fetch(:recipe_ids, [])
    )

    if @meal_plan.save
      redirect_to action: "index"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @meal_plan.update!(meal_plan_params)

    redirect_to action: "index"
  end

  def past_meal_plans
    @pagy, @past_meal_plans = pagy(
      :offset,
      MealPlan.past.order(end_date: :desc)
      .includes(:recipes).where.not(recipes: { id: nil }), limit: 3)
  end

  def upcoming_meal_plans
    @upcoming_meal_plans = MealPlan.future.order(start_date: :asc)
  end

  def destroy
    @meal_plan.destroy!
    redirect_to meal_plans_url, notice: "Meal plan was successfully deleted."
  end

  def generate_shopping_list
    render json: @meal_plan.recipes.map(&:ingredients).join("\n").to_json
  end

  private

  def set_meal_plan
    @meal_plan = MealPlan.find(params[:id])
  end

  def available_recipes
    @available_recipes = Recipe.all
  end

  def meal_plan_params
    params.require(:meal_plan).permit(:start_date, :end_date, recipe_ids: [])
  end
end

app/helpers/meal_plans_helper.rb
module MealPlansHelper
  def plan_meal_url(plan_meal_id)
    # TODO: hostname should be set dynamically
    Rails.logger.info(plan_meal_id)
    "http://localhost:3000/meal-plan-meals/#{plan_meal_id}"
  end
end

app/views/meal_plans/_form.html.erb
<%= form_with(model: meal_plan, class: "flex flex-col") do |form| %>
  <% if meal_plan.errors.any? %>
    <div id="error_explanation">
      <ul class="">
        <% meal_plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="flex flex-col my-4">
    <div class="flex sm:flex-row flex-col my-2">
    <div class="sm:pr-4 sm:my-0 my-2">
      <div class="pb-2">
        <span>
          <%= form.label :start_date %>
        </span>
      </div>
      <input type="date" id="meal_plan_start_date" name="meal_plan[start_date]" value="<%= meal_plan.start_date || Date.today %>"/>
    </div>

    <div class="sm:pl-4 sm:my-0 my-2">
      <div class="pb-2">
        <span>
          <%= form.label :end_date %>
        </span>
      </div>
      <input type="date" id="meal_plan_end_date" name="meal_plan[end_date]" value="<%= 6.days.after(Date.today) %>"/>
    </div>
    </div>

    <div class="flex flex-col my-2">
      <%= form.label :recipes, class: "pb-2" %>
      <%= form.collection_check_boxes :recipe_ids, Recipe.all, :id, :name do |recipe_option| %>
        <div class="flex gap-x-2">
          <%= recipe_option.check_box %>
          <%= recipe_option.label %>
        </div>
      <% end %>
    </div>
  </fieldset>

  <fieldset class="flex flex-col gap-y-2 my-4">
    <div class="flex gap-x-2">
      <%= form.button @meal_plan.new_record? ? "New meal plan" : "Save", class: primary_button_classes %>
      <%= button_to 'Back', meal_plans_path, :secondary%>
    </div>

    <div>
      <% unless @meal_plan.new_record? %>
        <%= button_to "Delete",
          @meal_plan,
          :tertiary,
          method: :delete,
          data: { turbo_confirm: "Are you sure?", turbo_method: :delete }
        %>
      <% end %>
    </div>
  </fieldset>
<% end %>

app/views/meal_plans/edit.html.erb
<%= render 'form', meal_plan: @meal_plan %>

app/views/meal_plans/index.html.erb
<h1 class="text-xl sm:text-4xl font-bold text-red-400">This Week We Shall Mostly Be Eating</h1>

<% if @current_meal_plan.nil? %>
  <p>Nothing :(</p>
<% else %>
  <div class="font-bold">
    <p><%= @current_meal_plan.start_date.to_formatted_s(:long) %> --> <%= @current_meal_plan.end_date.to_formatted_s(:long) %></p>
  </div>
  <ul class="flex flex-col gap-y-2">
    <% @current_meal_plan.meals.each do |meal| %>
      <li>
      <input
        id=<%= "checkbox-meal-#{meal.id}" %>
             class="form-check-input ms-1"
             type="checkbox"
             data-controller="checkbox"
             data-action="checkbox#toggle"
             data-checkbox-target="value"
             data-checkbox-url-value=<%= update_eaten_status_meal_path(meal) %>
          <% if meal.eaten? %>
            checked
          <% end %>
          >
        <%= meal.name %>
        <% if meal.recipe_book_name.present? %>
          (<%= meal.recipe_book_name %>)
        <% end %>
      </li>
    <% end %>
  </ul>

  <div 
    class="flex flex-col space-y-2"
    data-controller="populate-input" data-populate-input-url-value=<%= shopping_list_meal_plan_path(@current_meal_plan) %>>
    <div>
      <button class="" data-action="populate-input#populateInput">Generate Shopping List</button>
    </div>

    <div class="flex flex-col space-y-2 hidden" data-populate-input-target="inputContainer" data-controller="clipboard">
      <textarea id="shopping-list-input" class="resize-none rounded-md border-2 border-blue-500 shadow-sm h-32 w-fit"
        data-populate-input-target="input" data-clipboard-target="source"></textarea>

      <div>
        <button class="" data-action="clipboard#copy">Copy To Clipboard</button>
      </div>
      <div id="alert-placeholder" data-clipboard-target="alertPlaceholder"></div>
    </div>
  </div>
<% end %>

<div class="flex gap-x-2">
  <%= button_to "New plan", new_meal_plan_path, :primary %>
  <% unless @current_meal_plan.nil? %>
    <%= button_to "Edit", edit_meal_plan_path(@current_meal_plan), :secondary %>
  <% end %>
</div>

<%= button_to 'Past Weeks', past_meal_plans_path, :tertiary %>

app/views/meal_plans/new.html.erb
<h1 class="text-xl sm:text-4xl font-bold">New Meal Plan</h1>

<%= render 'form', meal_plan: @meal_plan %>

app/views/meal_plans/past_meal_plans.html.erb
<h1 class="text-xl sm:text-4xl font-bold text-red-400">In Past Weeks We Have Mostly Been Eating</h1>

<% unless @past_meal_plans.present? %>
  <p> Nothing :(</p>
<% else %>
  <div class="flex flex-col gap-y-4">
    <% @past_meal_plans.each do |plan| %>
      <div class="my-2">
        <h2 class="font-bold"><%= "#{plan.start_date} -> #{plan.end_date}" %></h2>
        <ul class="flex flex-col gap-y-2">
          <% plan.recipes.each do |recipe| %>
            <li><%= recipe.name %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
<% end %>

<div class="flex-col gap-y-4">
  <div class="flex gap-x-2 my-2">

    <%== @pagy.series_nav %>
  </div class="my-2">
  <%= button_to 'Current Plan', meal_plans_path, :tertiary %>
</div>