config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root to: "meal_plans#index"

  resources :meal_plans, path: "/meal-plans" do
    collection do
      get "past", to: "meal_plans#past_meal_plans"
    end
    member do
      get "shopping-list", to: "meal_plans#generate_shopping_list"
    end
  end

  resources :recipe_books, path: "/recipe-books" do
    collection do
      get "search", to: "recipe_books#search"
    end
  end
  resources :recipes

  resources :meals do
    member do
      put "update_eaten_status"
    end
  end

  resources :labels
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :recipe_book, optional: true

  has_many :meals, dependent: :delete_all
  has_many :meal_plans, through: :meals

  has_and_belongs_to_many :labels

  validates :name, presence: true
  validates :page_number, numericality: { only_integer: true, allow_nil: true }
  validates :recipe_book, presence: true, if: -> { page_number.present? }

  def recipe_book_name
    recipe_book&.name
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  def index
    @recipes = Recipe.all
  end

  def show; end

  def new
    @recipe = Recipe.new
  end

  def edit; end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to action: "index"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to action: "index"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_url
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    cleaned_params = params.require(:recipe).permit(:name, :recipe_book_id, :page_number, :ingredients, label_ids: [])

    cleaned_params[:ingredients] = cleaned_params[:ingredients].strip if cleaned_params[:ingredients]

    cleaned_params
  end
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, data: { controller: "form-field-state" }) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation" class="text-red-400 font-bold">
      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="flex flex-col my-4">
    <div class="my-2 flex gap-x-2">
      <%= form.label :name %>
      <%= form.text_field :name, class: "rounded-sm border border-slate-400 border-solid" %>
    </div>

    <div class="my-2 flex gap-x-2">
      <%= form.label :recipe_book %>
      <%= form.select :recipe_book_id,
        RecipeBook.all.collect { |b| [ b.name, b.id ] },
        { include_blank: "" },
        { class: "bg-white rounded-sm border border-slate-400 border-solid p-1", data: { "form-field-state-target": "trigger", action: "change->form-field-state#updateDependentState" } } %>
    </div>

    <div class="my-2 flex gap-x-2">
      <%= form.label :page_number %>
      <%= form.text_field :page_number, class: "rounded-sm border border-slate-400 border-solid", data: { "form-field-state-target": "dependent" }, disabled: true %>
    </div>

    <div class="my-2 flex flex-col gap-y-2" >
      <%= form.label :ingredients %>
      <%= form.text_area :ingredients,
        class: "resize-none grow-0 shrink-0 rounded-sm border border-slate-400 border-solid sm:w-64 h-48 p-1" %>
      <div class="font-light text-sm">
        Enter ingredients separated by a comma or newline
      </div>
    </div>

    <div class="my-2 flex gap-x-2">
      <%= form.label :labels %>
      <%= form.collection_check_boxes :label_ids, Label.all, :id, :name,
        { class: "flex gap-x-4" } do |b| %>
        <% b.label { b.check_box + " " + b.text } %>
      <% end %>
    </div>
  </fieldset>

  <fieldset class="flex flex-col gap-y-2 my-4">
    <div class="flex gap-x-2">
      <%= form.button "Save", class: primary_button_classes %>
      <%= button_to 'Back', recipes_path, :secondary%>
    </div>

    <div>
      <% unless @recipe.new_record? %>
        <%= button_to "Delete",
          @recipe,
          :tertiary,
          method: :delete,
          data: { turbo_confirm: "Are you sure?", turbo_method: :delete }
        %>
      <% end %>
    </div>
  </fieldset>
<% end %>

app/views/recipes/edit.html.erb
<h1 class="text-xl sm:text-4xl font-bold">Editing <%= @recipe.name %></h1>

<%= render 'form', recipe: @recipe %>

app/views/recipes/index.html.erb
<h1 class="text-xl sm:text-4xl font-bold">Recipes</h1>

<ul class="flex flex-col gap-y-4">
  <% @recipes.each do |recipe| %>
    <li>
      <div class="flex flex-row items-center gap-x-4">
        <%= button_to recipe.name, recipe, :tertiary %>
        <% if recipe.labels.any? %>
          <div class="flex gap-x-2 flex-wrap">
            <% recipe.labels.each do |label| %>
              <span class="text-xs bg-gray-200 rounded px-2 py-1"><%= label.name %></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

<%= button_to "New recipe", new_recipe_path, :primary %>

app/views/recipes/new.html.erb
<h1 class="text-xl sm:text-4xl font-bold">New Recipe</h1>

<%= render 'form', recipe: @recipe %>

app/views/recipes/show.html.erb
<h1 class="text-xl sm:text-4xl font-bold"><%= @recipe.name %></h1>

<% unless @recipe.recipe_book.nil? %>
  <p>
  <strong>Recipe Book:</strong>
    <%= link_to @recipe.recipe_book.name, recipe_book_path(@recipe.recipe_book) %>
  </p>
  <% unless @recipe.page_number.nil? %>
    <p>
    <strong>Page Number:</strong>
      <%= @recipe.page_number %>
    </p>
  <% end %>
<% end %>

<% if @recipe.labels.any? %>
  <p>
    <strong>Labels:</strong>
    <div class="flex gap-x-2 flex-wrap">
      <% @recipe.labels.each do |label| %>
        <%= link_to label.name, label, class: "text-xs bg-gray-200 rounded px-2 py-1" %>
      <% end %>
    </div>
  </p>
<% end %>

<% unless @recipe.ingredients.blank? %>
  <strong>Ingredients</strong>
  <div><%= simple_format(@recipe.ingredients) %></div>
<% end %>


<div class="flex gap-x-2">
  <%= button_to "Edit", edit_recipe_path(@recipe), :primary %>
  <%= button_to "Back", recipes_path, :secondary %>
</div>