config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root to: "meal_plans#index"

  resources :meal_plans, path: "/meal-plans" do
    collection do
      get "past", to: "meal_plans#past_meal_plans"
    end
    member do
      get "shopping-list", to: "meal_plans#generate_shopping_list"
    end
  end

  resources :recipe_books, path: "/recipe-books" do
    collection do
      get "search", to: "recipe_books#search"
    end
  end
  resources :recipes

  resources :meals do
    member do
      put "update_eaten_status"
    end
  end

  resources :labels
end

app/models/label.rb
class Label < ApplicationRecord
  has_and_belongs_to_many :recipes

  validates :name, presence: true
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: %i[show edit update destroy]

  def index
    @labels = Label.all
  end

  def show; end

  def new
    @label = Label.new
  end

  def edit; end

  def create
    @label = Label.new(label_params)

    if @label.save
      redirect_to @label, notice: "Label was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @label.update(label_params)
      redirect_to @label, notice: "Label was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @label.destroy
    redirect_to labels_url, notice: "Label was successfully destroyed."
  end

  private

  def set_label
    @label = Label.find(params[:id])
  end

  def label_params
    params.require(:label).permit(:name)
  end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_with(model: label) do |form| %>
  <% if label.errors.any? %>
    <div id="error_explanation" class="text-red-400 font-bold">
      <ul>
        <% label.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="flex flex-col my-4">
    <div class="my-2 flex gap-x-2">
      <%= form.label :name %>
      <%= form.text_field :name, class: "rounded-sm border border-slate-400 border-solid" %>
    </div>
  </fieldset>

  <fieldset class="flex flex-col gap-y-2 my-4">
    <div class="flex gap-x-2">
      <%= form.button "Save", class: primary_button_classes %>
      <%= button_to 'Back', labels_path, :secondary %>
    </div>

    <div>
      <% unless @label.new_record? %>
        <%= button_to "Delete",
          @label,
          :tertiary,
          method: :delete,
          data: { turbo_confirm: "Are you sure?", turbo_method: :delete }
        %>
      <% end %>
    </div>
  </fieldset>
<% end %>

app/views/labels/edit.html.erb
<h1 class="text-xl sm:text-4xl font-bold">Edit Label</h1>

<%= render 'form', label: @label %>

app/views/labels/index.html.erb
<h1 class="text-xl sm:text-4xl font-bold">Labels</h1>

<ul class="flex flex-col">
  <% @labels.each do |label| %>
    <li><%= button_to label.name, label, :tertiary %></li>
  <% end %>
</ul>

<%= button_to "New label", new_label_path, :primary %>

app/views/labels/new.html.erb
<h1 class="text-xl sm:text-4xl font-bold">New Label</h1>

<%= render 'form', label: @label %>

app/views/labels/show.html.erb
<h1 class="text-xl sm:text-4xl font-bold"><%= @label.name %></h1>

<% if @label.recipes.any? %>
  <strong>Recipes</strong>
  <ul class="flex flex-col">
    <% @label.recipes.each do |recipe| %>
      <li><%= link_to recipe.name, recipe %></li>
    <% end %>
  </ul>
<% end %>

<div class="flex gap-x-2">
  <%= button_to "Edit", edit_label_path(@label), :primary %>
  <%= button_to "Back", labels_path, :secondary %>
</div>