config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root to: "meal_plans#index"

  resources :meal_plans, path: "/meal-plans" do
    collection do
      get "past", to: "meal_plans#past_meal_plans"
    end
    member do
      get "shopping-list", to: "meal_plans#generate_shopping_list"
    end
  end

  resources :recipe_books, path: "/recipe-books" do
    collection do
      get "search", to: "recipe_books#search"
    end
  end
  resources :recipes

  resources :meals do
    member do
      put "update_eaten_status"
    end
  end

  resources :labels
end

app/views/layouts/_navbar.html.erb
<nav class="bg-red-400 w-screen sm:w-fit sm:min-h-screen">
  <div class="my-auto py-2">
    <div class="relative flex flex-row sm:flex-col h-16 items-center justify-between">
      <div class="flex flex-row sm:flex-col flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-col flex-shrink-0 items-center">
          <%= image_tag "logo.png", class:"h-8 w-auto", alt:"Your Company" %>
        </div>

          <div class="flex flex-row sm:flex-col space-x-4 sm:space-x-0 sm:space-y-4 my-2 mx-2">
            <%= link_to "Plans", meal_plans_path, class:"rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" %>
            <%= link_to "Recipes", recipes_path, class:"rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" %>
            <%= link_to "Recipe Books", recipe_books_path, class:"rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" %>
            <%= link_to "Labels", labels_path, class:"rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" %>
          </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Meals On Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="flex flex-col sm:flex-row">
    <%= render "layouts/navbar" %>
    <main class="container mx-auto px-5 py-5 flex flex-col space-y-4">
      <%= yield %>
    </main>
  </body>
</html>